name: Auto-sort *.properties files (with sensitive line removal)

on:
  push:
    paths:
      - '**/*.properties'
  pull_request:
    paths:
      - '**/*.properties'

jobs:
  auto-sort-properties:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean and sort all *.properties files
        run: |
          set -e
          shopt -s globstar nullglob
          changed=false
          
          for file in **/*.properties; do
            temp=$(mktemp)
            # Remove lines that match any sensitive keywords or patterns
            grep -v -Ei '^(.*(api[_-]?key|token|webhook|password|username|auth|secret|endpoint)[^=]*=|https?://|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)' "$file" \
              | sort > "$temp"

            if ! cmp -s "$file" "$temp"; then
              echo "Cleaning and sorting $file"
              mv "$temp" "$file"
              git add "$file"
              changed=true
            else
              rm "$temp"
            fi
          done

          if $changed; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git commit -m "Cleaned and auto-sorted *.properties files"
            git push
          else
            echo "No changes needed — all files clean and sorted"
          fi
