name: Auto-sort *.properties files

on:
  push:
    paths:
      - '**/*.properties'
  pull_request:
    paths:
      - '**/*.properties'

jobs:
  auto-sort-properties:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sort all *.properties files alphabetically
        run: |
          set -e
          shopt -s globstar nullglob
          changed=false
          
          for file in **/*.properties; do
            temp=$(mktemp)
            sort "$file" > "$temp"
            if ! cmp -s "$file" "$temp"; then
              echo "Sorting $file"
              mv "$temp" "$file"
              git add "$file"
              changed=true
            else
              rm "$temp"
            fi
          done

          if $changed; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git commit -m "Auto-sorted *.properties files"
            git push
          else
            echo "All *.properties files already sorted"
          fi
